[package]
name = "rust-parallel"
version = "0.1.0"
edition = "2021"

[dependencies]
num = "0.4.3"

[dependencies.rayon]
version = "1.10.0"
optional = true

[features]
default = ["rayon"]
rayon = ["dep:rayon"]
